//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcUrünTakipSistemi.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Satislar
    {
        public int SatisID { get; set; }
        public Nullable<int> UrunID { get; set; }
        public Nullable<int> PersonelID { get; set; }
        public Nullable<int> MusteriID { get; set; }
        public Nullable<decimal> Fiyat { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
    
        public virtual Musteriler Musteriler { get; set; }
        public virtual Personel Personel { get; set; }
        public virtual Urunler Urunler { get; set; }
    }
}
